# Web Scraping Twitter's content 
# 02-DataCollect

# Installing the necessary packages
# install.packages("tidyverse")
# install.packages("twitteR")
# install.packages("tidytext")
# install.packages("gridExtra")
# install.packages("stopwords")

# Loading the necessary packages
library(tidyverse)
library(twitteR)
library(tidytext)
#library(gridExtra)


# Setting up Twitter authentication
# You need to have a twitter account. If you do not have one go to http://twitter.com/signup and 
# set one up. Also you need to have a mobile number as part of this account.
# 
# Now that you have created a twitter account you need to go to https://apps.twitter.com and sign up
# to a development account with your twitter account. You'll have to answer some questions regarding
# the use you will make with that account.
# 
# Once you get your Twitter development account, go back to https://apps.twitter.com and click on the 
# “Create New App” button. When on the Create an App screen, there are some required fields to fill:
# "App name", "Application description", "Website URL" and "Tell us how this app will be used".
#
# The name of the application must be unique so this may take a few tries. The description needs to be 
# at least 10 character long and at most 200 characteres long. The website field is any that people can
# reach you, like a Github or a personal webpage.The last required field, "Tell us how this app will be 
# used" needs to be at least 100 characters long. 
#
# After the creation, click on the "Keys and tokens" tab, then on the button "Create" under the 
# "Access token & access token secret" section. Those keys and tokens are secret, don't show them to anyone.
# You will need them to the next step, to make your analysis.

# Creating objetcs with your API key and access token:
consumer_key <- "" # consumer_api_key
consumer_secret <- "" # consumer_api_secret_key
access_token <- "" # access_token
access_secret <- "" # access_token_secret

# Setting up the authentication for a twitteR session. Use option 1 or 2 when asked.
# For more information, see the help of the following function.
setup_twitter_oauth(consumer_key, consumer_secret, access_token, access_secret)

# Searching for the entities previously stablished on the summary of this project 
# For more informations, see the help of the following function.
twitters_search <- searchTwitter("President Trump", n = 2000, lang = "en")

# Converting objects to data frames, then removing objects that won't be needed
# For more information, see the help of these functions.
twitters_search_df <- twListToDF(twitters_search)
twitters_search_df <- as_tibble(twitters_search_df)

# Just in case you need this data frame latter. 
# See dput() documentation for more information.
# dput(twitters_search_df, file = "twitters_search_df.R") 

# Before loading the script generated by the dput function, you must create an object 
# with its content, adding the following code at the beginning of the script: "twitters_search_df = "
# I highly recommend executing this script with the "Source" option, that in RStudio has
# the shortcut "CTRL + SHIFT + S". Or you can use the following command: source("twitters_search_df.R")
# Otherwise, the execution/loading will be very slow (as it has about seven thousand lines).

